moved default code into run_all_policies function. if commandline args are specified, run specified policies, otherwise, just run them all.

diff --git a/snapbackup b/snapbackup
--- a/snapbackup
+++ b/snapbackup
@@ -85,24 +85,40 @@ function policy_abs_path () {
 	echo $POLICY
 }
 
+function run_all_policies () {
+	POLICIES=`ls "$SCRIPTPATH/policies"`
 
+	# check to make sure there is at least one policy loaded
+	if [[ -z $POLICIES ]]; then
+		echo "No policies were found. Cannot continue the backup."
+		echo "Sample policies are located in the policies-available directory"
+		echo "Symlink polices from policies-available to policies to enable them."
+		echo ""
+		exit 1
+	fi
 
-POLICIES=`ls "$SCRIPTPATH/policies"`
+	for policy in $POLICIES
+	do
+		# parse out the policy name from the filename ( ie: "mysql.sh" => "mysql" )
+		POLICY_NAME=`echo $policy | cut -d'.' -f1`
 
-# check to make sure there is at least one policy loaded
-if [[ -z $POLICIES ]]; then
-	echo "No policies were found. Cannot continue the backup."
-	echo "Sample policies are located in the policies-available directory"
-	echo "Symlink polices from policies-available to policies to enable them."
-	echo ""
-	exit 1
+		# execute the policy and receive list of files ready for backup.
+		run_policy $policy
+	done
+}
+
+############################
+# START PROGRAM:
+############################
+
+# if any commandline arguments are supplied, run those policies, otherwise, run all policies
+
+if [[ $# -eq 0 ]]; then
+	run_all_policies
+else
+	for policy in $@; do
+		run_policy $policy
+	done
 fi
 
-for policy in $POLICIES
-do
-	# parse out the policy name from the filename ( ie: "mysql.sh" => "mysql" )
-	POLICY_NAME=`echo $policy | cut -d'.' -f1`
-	
-	# execute the policy and receive list of files ready for backup.
-	run_policy $policy
-done
+
